allowLineBreaksInTitles: false
color: violet
description: null
fieldLayouts:
  eb77256e-c09a-4da9-b4e4-f6d34fe0df51:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:1d7830ee-7479-40b2-96b0-17200bd14633'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-14T11:44:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 17c0c6a4-80a6-4cef-84f4-ebefe3af9d39 # Text - Multi
            handle: headline
            instructions: null
            label: Headline
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d7830ee-7479-40b2-96b0-17200bd14633
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-16T11:31:53+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 048ca300-746f-47c7-88e8-03271c08c318 # Rich Text - Simple
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f0be684-f690-4928-92e0-e614fd7efe16
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-29T10:16:23+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2078d68-c6cf-42ee-ad68-931b8a4b5cdb # Link - Native
            handle: button
            instructions: null
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8731b252-877d-4cfa-80b2-c380c4af26be
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 161b50d7-4fd5-4b0e-aa62-81f5857f27b1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-21T09:46:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3c6dd0d6-6cbf-415f-a6fe-3bc205817b94 # Anchor
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2178d45-69d4-4c66-8a2f-3cf7e1c8efb2
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 16667a60-8683-4eb5-8a85-02074cf93715
        userCondition: null
    thumbFieldKey: null
handle: blockCta
hasTitleField: false
icon: bullhorn
name: CTA
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
