color: null
description: null
fieldLayouts:
  9a1d0e31-4213-4957-8767-6df4fee667ff:
    cardThumbAlignment: end
    generatedFields:
      -
        handle: seoHideGenerated
        name: 'Seo Hide Generated'
        template: '{{ object.seo.seoHide ? 1 : 0 }}'
        uid: d74fbbee-f4c8-448b-b8fc-d5723a6d0f07
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-14T11:14:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af90ca47-37e3-4960-a865-15e25dd85c33
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-14T11:42:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17c0c6a4-80a6-4cef-84f4-ebefe3af9d39 # Text - Multi
            handle: headline
            includeInCards: false
            instructions: null
            label: Überschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f333c3f6-b95e-4720-8b85-bac84b0fd6bf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-14T11:14:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b6dd59c-982a-43fa-908f-143e8ef509f2 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6268711e-041f-4ba2-ac1f-69075f35f133
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-14T11:14:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dbbb65c3-5ee4-438d-8436-b6e57e74daf5 # Relation - Categories
            handle: null
            includeInCards: false
            instructions: null
            label: Categories
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ebd48e4-16ae-438b-88db-b7c32dac5dbd
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-07T08:51:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 63c16184-84bf-4b0d-9617-96987ad1df39 # Card
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8400975a-3c66-4f88-8655-32c392a5a8df
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-07T09:41:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b176366b-d2cd-4172-bbb5-f64769af3719 # Map
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f45d57a-6089-4476-9875-732dfa47a1a0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-13T08:54:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d1810b84-cc13-409f-a229-ed19ee97748e # Url
            handle: null
            includeInCards: false
            instructions: null
            label: 'External Url'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96a98d05-9c97-4424-b5b3-b60a09dafe54
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T07:54:19+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2ca232d5-f845-462b-81df-eaed2e95db52
            userCondition: null
          -
            dateAdded: '2025-05-12T07:53:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a5600e8-07a6-4292-bc21-d0e142d9dc22 # Matrix - Builder
            handle: null
            includeInCards: false
            instructions: null
            label: Builder
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfeb28d2-af3f-4b63-b26a-fbae3df46184
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e664a593-4a23-45e1-9fc8-6e0b55ad80ac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-07T08:48:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5bf4ae8e-4fcb-4ed0-bb07-7dbbb4c59050 # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcfbc11b-7294-42a8-9834-1904eb892db5
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 3f68c259-b92d-4518-ba2a-902a2332a1cb
        userCondition: null
handle: etBlogEntry
hasTitleField: true
icon: page
name: 'Blog Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
