columnSuffix: null
handle: richtextBuilder
instructions: null
name: 'Rich Text - Builder'
searchable: true
settings:
  advancedLinkFields:
    - target
    - ariaLabel
    - download
  availableTransforms: ''
  availableVolumes:
    - d55b1175-f5cd-4977-8625-4333d431a8f6 # Files
  characterLimit: null
  css: '.ui-teaser { font-weight: bold; font-size: 120%; }'
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: d55b1175-f5cd-4977-8625-4333d431a8f6 # Files
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b049044a-c809-41e6-9e27-43e22b6c394b # Accordion
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - 94ef075b-ba6b-4c18-9200-1ed39a0e1d1e # Code
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - 82e2a38f-ac8e-4b00-8b0c-d9ab4dc9ad7d # Media
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - 9b278eea-1d19-4a12-87d0-8fd0d4ccade2 # Gallery
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - f1af4550-8b3b-46b7-926d-f0807cac7bf3 # Cards
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - 2cec4e62-8325-4329-b76c-d5c7ae7af576 # Buttons
        -
          - expanded
          - true
    -
      __assoc__:
        -
          - uid
          - 76206244-6c91-4de1-b3d0-68c5d6a77369 # CTA
        -
          - expanded
          - true
  fullGraphqlData: false
  headingLevels:
    - '1'
    - '2'
    - '3'
    - '4'
  imageEntryTypeUid: 76206244-6c91-4de1-b3d0-68c5d6a77369 # CTA
  imageFieldUid: 60975007-2c9c-4def-920c-c569249360dc
  imageMode: img
  js: "return {\r\n  style: {\r\n    definitions: [\r\n      {\r\n        name: 'Teaser',\r\n        element: 'p',\r\n        classes: [\r\n          'ui-teaser',\r\n        ],\r\n      }\r\n    ],\r\n  },\r\n}"
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - createEntry
    - '|'
    - heading
    - style
    - '|'
    - bold
    - underline
    - italic
    - link
    - blockQuote
    - horizontalLine
    - '|'
    - bulletedList
    - numberedList
    - '|'
    - removeFormat
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
